# Form implementation generated from reading ui file 'game_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 704)
        MainWindow.setStyleSheet("background: #202020;\n"
"color: #d9d9d9;\n"
"font: 14pt \"Source Code Pro\";")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 721, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 12pt \"Source Code Pro\";\n"
"border: 1px solid #b8b8b8")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 12pt \"Source Code Pro\";\n"
"border: 1px solid #b8b8b8")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setStyleSheet("font: 12pt \"Source Code Pro\";\n"
"border: 1px solid #b8b8b8")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 721, 111))
        self.label_4.setStyleSheet("font: italic 28pt \"Source Code Pro\";\n"
"background: #292929;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 220, 721, 481))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 711, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_7.setStyleSheet("background: #292929;\n"
"border: 3px solid #404040;\n"
"border-radius: 10px;\n"
"padding: 5px")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton.setStyleSheet("background: #292929;\n"
"border: 3px solid #404040;\n"
"border-radius: 10px;\n"
"padding: 5px")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_6.setStyleSheet("background: #292929;\n"
"border: 3px solid #404040;\n"
"border-radius: 10px;\n"
"padding: 5px")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_8.setStyleSheet("background: #292929;\n"
"border: 3px solid #404040;\n"
"border-radius: 10px;\n"
"padding: 5px")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 711, 31))
        self.label_10.setStyleSheet("border: 1px solid #b8b8b8;\n"
"padding: 5px;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 721, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        self.label_14.setStyleSheet("font: 12pt \"Source Code Pro\";\n"
"border: 1px solid #b8b8b8")
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        self.label_15.setStyleSheet("font: 12pt \"Source Code Pro\";\n"
"border: 1px solid #b8b8b8")
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Деньги: 0$"))
        self.label_3.setText(_translate("MainWindow", "Знание: 0"))
        self.label.setText(_translate("MainWindow", "Студенты: 0"))
        self.label_4.setText(_translate("MainWindow", "2 + 2 = 4"))
        self.label_5.setText(_translate("MainWindow", "Взять умного студента"))
        self.pushButton_7.setText(_translate("MainWindow", "15$"))
        self.pushButton.setText(_translate("MainWindow", "100$"))
        self.label_11.setText(_translate("MainWindow", "Взять среднего студента"))
        self.label_12.setText(_translate("MainWindow", "Взять плохого студента"))
        self.pushButton_6.setText(_translate("MainWindow", "50$"))
        self.label_13.setText(_translate("MainWindow", "Взять случайного студента"))
        self.pushButton_8.setText(_translate("MainWindow", "Бесплатно"))
        self.label_10.setText(_translate("MainWindow", "Увеличение количества студентов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Студенты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Заработок"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Курсы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Информация"))
        self.label_14.setText(_translate("MainWindow", "Доход: 0^0"))
        self.label_15.setText(_translate("MainWindow", "Уровень: 0"))
